source 'https://github.com/CocoaPods/Specs.git'

target 'NPCricket', :exclusive => true do
  pod "NPCricket", :path => "../"
  pod 'AFNetworking', '~> 2.4.1'

end

target 'Tests', :exclusive => true do
  pod "NPCricket", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
